version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - GIN_MODE=release 
      - DB_HOST=db
      - REDIS_HOST=redis

  frontend:
    build: ./front/posts-front
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: lozinka123
      MYSQL_DATABASE: posts
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
